spring:
  application:
    name: auto-test-tool
  profiles:
    active: local
server:
  port: 9003

# log
logging:
  path: ${user.home}/logs/auto-test-tool

json:
  file:
    path: usr/local/eshop/json/
