spring:
  application:
    name: auto-test-tool
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
server:
  port: 9003

# log
logging:
  path: ${user.home}/logs/auto-test-tool
